# Reusable logging config to prevent log files from eating your hard drive
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:

  # --- Database ---
  db:
    image: postgres:15-alpine
    container_name: occacia-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      # Note: If change this password later, you must run 'down -v' to reset the volume
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Set DB_PASSWORD in .env}
      POSTGRES_DB: ${DB_NAME:-occacia_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-occacia_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging

  # --- Database Migrations ---
  # This container wakes up, upgrades the database schema to the latest version, and goes to sleep.
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Uses the internal Docker network to connect to the 'db' container
      DATABASE_URL: postgresql://${DB_USER:-admin}:${DB_PASSWORD}@db:5432/${DB_NAME:-occacia_db}
    command: [ "sh", "-c", "alembic upgrade head" ]
    restart: "no"
    profiles: [ "tools" ]
    logging: *default-logging

volumes:
  postgres_data:
