"""Baseline master schema

Revision ID: 67d53627a8d9
Revises: 
Create Date: 2026-03-15 00:09:19.313810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d53627a8d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_provider', sa.String(), nullable=True),
    sa.Column('calendar_default_id', sa.String(), nullable=True),
    sa.Column('calendar_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_oauth_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(timezone=True), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('preferences_json', sa.JSON(), nullable=True),
    sa.Column('food_preferences', sa.JSON(), nullable=True),
    sa.Column('color_preferences', sa.JSON(), nullable=True),
    sa.Column('music_preferences', sa.JSON(), nullable=True),
    sa.Column('personality_tags', sa.JSON(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_customer_id'), 'personas', ['customer_id'], unique=False)
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.create_index(op.f('ix_personas_persona_id'), 'personas', ['persona_id'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('location_base', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_business_name'), 'vendors', ['business_name'], unique=False)
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=True)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_vendor_id'), 'vendors', ['vendor_id'], unique=True)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_per_head', sa.Float(), nullable=True),
    sa.Column('min_guests', sa.Integer(), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('location_coverage', sa.String(), nullable=True),
    sa.Column('blocked_dates', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_vendors_vendor_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_business_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_personas_persona_id'), table_name='personas')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_index(op.f('ix_personas_customer_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###