export const ROUTES = {
  HOME: '/',
  CUSTOMER: {
    LOGIN: '/customer/auth/login',
    FORGOT_PASSWORD: '/customer/auth/forgot-password',
    RESET_PASSWORD: '/customer/auth/reset-password',
    DASHBOARD: '/customer/dashboard',
    REGISTER: '/customer/auth/register',
    VERIFY_EMAIL: '/customer/auth/verify-email',
    EVENTS: '/customer/events',
    EVENTS_NEW: '/customer/events/new',
    EVENT_CHAT: (eventId: string) => `/customer/events/${eventId}/chat`,
    EVENT_TRACKING: (eventId: string) => `/customer/events/${eventId}`,
    EVENT_DRAFT_REVIEW: (eventId: string) => `/customer/events/${eventId}/draft`,
    EVENT_RECOMMENDATIONS: (eventId: string) => `/customer/events/${eventId}/recommendations`,
    EVENT_PACKAGES: (eventId: string) => `/customer/events/${eventId}/packages`,
    EVENT_PACKAGE_DETAIL: (eventId: string, packageId: string) => `/customer/events/${eventId}/packages/${packageId}`,
    EVENT_PACKAGE_CUSTOMIZE: (eventId: string, packageId: string) => `/customer/events/${eventId}/packages/${packageId}/customize`,
    EVENT_PACKAGE_CONFIRM: (eventId: string, packageId: string) => `/customer/events/${eventId}/packages/${packageId}/confirm`,
    EVENT_ORDER_CONFIRMATION: (eventId: string, packageOrderId: string) => `/customer/events/${eventId}/orders/${packageOrderId}`,
    PRODUCTS: '/customer/products',
    CART: '/customer/cart',
    ORDERS: '/customer/orders',
    PERSONA: '/customer/persona',
    PERSONA_NEW: '/customer/persona/new',
    PERSONA_DETAIL: (personaId: string) => `/customer/persona/${personaId}`,
  },
  VENDOR: {
    LOGIN: '/vendor/auth/login',
    REGISTER: '/vendor/auth/register',
    VERIFY_EMAIL: '/vendor/auth/verify-email',
    DASHBOARD: '/vendor/dashboard',
    ACTIVITIES: '/vendor/activities',
    PENDING_APPROVAL: '/vendor/auth/pending-approval',
    ACTIVATED: '/vendor/activated',
    PRODUCTS: '/vendor/products',
    ORDERS: '/vendor/orders',
    OFFERINGS: '/vendor/offerings',
    TASKS: '/vendors/tasks',
  },
  VENDORS: {
    DASHBOARD: '/vendors/dashboard',
    PENDING_APPROVAL: '/vendors/pending-approval',
  },
  ADMIN: {
    HOME: '/admin',
    LOGIN: '/admin/login',
    DASHBOARD: '/admin/dashboard',
    APPROVALS: '/admin/approvals',
    USERS: '/admin/users',
    CUSTOMERS: '/admin/customers',
    PENDING_VENDORS: '/admin/vendors/pending',
    SETTINGS: '/admin/settings',
  },
} as const;

export const ROUTES_ALIAS = {
  VENDOR_DASHBOARD: ROUTES.VENDOR.DASHBOARD,
  VENDOR_PENDING_APPROVAL: ROUTES.VENDOR.PENDING_APPROVAL,
  VENDOR_ACTIVATED: ROUTES.VENDOR.ACTIVATED,
  VENDOR_PRODUCTS: ROUTES.VENDOR.PRODUCTS,
} as const;
